### ISSUE TITLE
problem with eph compilation

### ISSUE THREAD

**Issue by fvalenciad** [LLNL/USER-EPH#2]
Dear developers,

We are trying to install the eph module in LAMMPS, however we have a recurrent compilation problem. The message is similar  for serial and mpi compilation. Just to be sure, we try the compilation in two different machines getting the same errors. We attach you the files with the hope that you can help us or telling us what we are doing wrong.

Many thanks in advance for your help.
Felipe.

[serial.txt](https://github.com/LLNL/USER-EPH/files/3836149/serial.txt)
[mpi.txt](https://github.com/LLNL/USER-EPH/files/3836150/mpi.txt)

**Comment by correaa** [comment]
Thanks @fvalenciad, I am curious what your `mpicxx --version` prints.

This function should be removed from the cpp file https://github.com/LLNL/USER-EPH/blob/afc92e9ec3228f10bf82b95e3753293b348092e1/eph_fdm.cpp#L22 because the function is already defined in the hpp.

**Comment by fvalenciad** [comment]
Hi @correaa ,
the output  of mpicxx --version:
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

Just in case, I delete the function but the compilation still not works.

**Comment by artuuuro** [comment]
Hi,
I forgot to remove the eph_fdm.cpp file which is not needed. My personal branch had the safety macros to disable it.

It should be fixed in the latest commit.

Artur

**Comment by artuuuro** [comment]
It is important to run make yes-user-eph after changing the sources in
USER-EPH folder, because LAMMPS copies files from USER-EPH into the src/
folder when you run make yes-user-eph.

Artur

**Comment by fvalenciad** [comment]
Dear @artuuuro,
with your suggestion the compilation works for both, serial and mpi.
Many thanks for your help!
Best regards,
Felipe
