### ISSUE TITLE
Dynamic Ce is buggy

### ISSUE THREAD

**Issue by artuuuro** [LLNL/USER-EPH#4]
Dynamic Ce is not correctly implemented and thus is not conserving energy.

**Comment by correaa** [comment]
We are fixing this at the moment

**Comment by artuuuro** [comment]
This is now fixed. I switched to using what Alfredo suggested. The evolution is tracked through E(T) <-> T(E) mapping which assumes monotonic E(T) function (this should always be the case). Initial tests show no temperature drift.
